### ISSUE TITLE
Função de busca por escolas está quebrada.

### ISSUE THREAD

**Issue by LucasMarcolino237** [clewertonx1/escolas-brasil#1]
A entrada que você adicionou na API parece ser para a busca de cidades dentro de um estado, no lugar do ".../cidades/nome=$`{nome}`" ela pede algo como ".../cidades/$`{siglaEstado}`" para retornar um JSON com todas as cidades do estado e seus respectivos códigos. Não sou muito experiente na área, mas estou disposto a colaborar com o pouco que eu sei e quem sabe nó dois possamos aprender juntos e fazer isso dar certo.

(Essa é uma das primeiras issues que eu faço aqui no GitHub, então mão sei muito bem como faze-la :rofl: )

**Comment by clewertonx1** [comment]
Vou da uma olhada mano

**Comment by clewertonx1** [comment]
Tinha errado o link mesmo mano, concertei, vlw por avisar <3 fico feliz que esteja tentando ajudar mano, eu tbm sou novo aqui pelo github

**Comment by ricardozv** [comment]
Vou tentar ajudar também, mas não sei como iniciar num projeto open source, uma coisa que vi já de início é o uso de var, muda pra const mano, var não é recomendado. Depois vou dar uma olhada com mais calma.

**Comment by clewertonx1** [comment]
@ricardozv Primeiro voce tem que fazer um fork do meu projeto, depois faz um git clone e começar a coda. quando tiver alguma funcionalidade nova tu abri um pull request aqui que eu dou uma olhada. 

Qualquer coisa me chama no telegram. 

OBRIGADO POR TA AJUDANDO 🧡

**Comment by ricardozv** [comment]
Opá! tranquilo irmão! Valeu, vou fazer isso agora, e depois reviso o código. 
Se ajudando a gente vai mais longe! abraço!

**Comment by clewertonx1** [comment]
Ja concertei
